-- Arizona Week 3 - Simple Migration for Supabase SQL Editor
-- Insert Arizona breweries and beer reviews to match existing Alabama/Alaska pattern

-- Insert Arizona beer reviews directly (following existing pattern)
INSERT INTO beer_reviews (id, blog_post_id, brewery_name, beer_name, beer_style, abv, rating, review_text, tasting_notes, unique_feature, review_date) VALUES
('c0a1d8f0-79c1-4255-87e4-4e73687cf572', 'arizona-day1-four-peaks-kilt-lifter', 'Four Peaks Brewing Company', 'Kilt Lifter', 'Scottish-Style Ale', 6.0, 4.2, 'WEEK 3 BEGINS: ARIZONA''S DESERT BREWING REVOLUTION! From the shadow of Tempe Butte comes Arizona''s brewing pioneer! Four Peaks opened in 1996 as the state''s first major craft brewery, and their Kilt Lifter remains the beer that introduced countless Arizonans to craft brewing.', 'Rich amber color with caramel malt sweetness and subtle hop balance. A warming Scottish ale that paradoxically refreshes in 115°F heat.', 'Arizona''s first major craft brewery, pioneering desert brewing since 1996', '2025-08-11'),

('c1b2e9f1-80d2-4366-98f5-5f84798dg683', 'arizona-day2-wilderness-refuge-ipa', 'Arizona Wilderness Brewing Company', 'Refuge IPA', 'American IPA', 6.8, 4.4, 'Day 2: Arizona Wilderness Refuge IPA - Sustainability Meets Flavor! Born in a founder''s garage and evolved into Arizona''s most environmentally conscious brewery. Uses 100% Arizona-grown Sinagua Malt and supports water conservation.', 'Bright citrus and pine hop character balanced by locally-grown malt sweetness. Unique terroir from Arizona-grown ingredients.', '100% Arizona-grown Sinagua Malt, water conservation offsetting program', '2025-08-12'),

('c2c3faf2-91e3-4477-a906-6095809eh794', 'arizona-day3-historic-piehole-porter', 'Historic Brewing Company', 'Piehole Porter', 'Porter', 5.5, 4.3, 'Day 3: Historic''s Piehole Porter - Dessert Innovation from Flagstaff! From the pines of Flagstaff comes Arizona''s most beloved dessert beer! Natural cherry and vanilla create a liquid cherry pie experience.', 'Rich, dark porter base enhanced with natural cherry and vanilla flavoring. Smooth, creamy texture with chocolate malt backbone.', 'Liquid cherry pie experience, brewed at 7,000 feet elevation', '2025-08-13'),

('c3d4fbf3-a2f4-4588-ba17-70a691fei8a5', 'arizona-day4-dragoon-ipa', 'Dragoon Brewing Company', 'Dragoon IPA', 'West Coast IPA', 7.3, 4.5, 'Day 4: Dragoon IPA - Tucson''s Uncompromising West Coast Classic! Dragoon embodies Tucson''s rebellious spirit. They brew only four year-round beers, focusing on quality over quantity.', 'Bold, aggressive hop character with fruity, floral, and citrus aromas. Clean malt backbone supports intense hop bitterness.', 'Only four year-round beers, quality over quantity philosophy', '2025-08-14'),

('c4e5fcf4-b3g5-4699-cb28-81b7a2gfj9b6', 'arizona-day5-santan-devils-ale', 'SanTan Brewing Company', 'Devil''s Ale', 'American Pale Ale', 5.5, 4.1, 'Day 5: SanTan''s Devil''s Ale - Sinfully Crisp Southwestern Style! With a devilish grin and Arizona attitude, this "sinfully crisp" pale ale embodies the playful irreverence that makes Arizona craft beer memorable.', 'Golden amber color with pronounced hop aroma. Pine and citrus flavors from Cascade, Centennial, and Simcoe hops.', 'Sinfully crisp finish perfect for 115°F desert heat', '2025-08-15'),

('c5f6gdf5-c4h6-47aa-dc39-92c8b3hgk0c7', 'arizona-day6-oak-creek-nut-brown', 'Oak Creek Brewery', 'Nut Brown Ale', 'English Brown Ale', 5.5, 4.0, 'Day 6: Oak Creek Nut Brown Ale - Sedona''s Red Rock Beauty! From Sedona''s stunning Tlaquepaque arts community comes this award-winning brown ale that captures the earthy, rich tones of red rock country.', 'Rich brown color that mirrors Sedona''s iconic sandstone formations. Nutty, caramel malt flavors with subtle hop balance.', 'Brewed in Sedona''s arts district since 1995, every pint comes with million-dollar views', '2025-08-16'),

('c6g7hef6-d5i7-48bb-ed4a-a3d9c4ihl1d8', 'arizona-day7-mother-road-tower-station', 'Mother Road Brewing Company', 'Tower Station IPA', 'American IPA', 6.8, 4.3, 'Day 7 FINALE: Mother Road''s Tower Station IPA - Route 66 Adventure Beer! Named for Historic Route 66, this award-winning IPA celebrates Arizona''s role in American adventure culture from Flagstaff''s high country.', 'Citrus and pine hop characteristics that evoke Arizona''s high-desert landscape. Clean, refreshing finish perfect for road trip adventures.', 'Named for Route 66, embodies the spirit of westward exploration and endless horizons', '2025-08-17');

-- Verify insertion
SELECT COUNT(*) as arizona_reviews_added FROM beer_reviews WHERE brewery_name LIKE '%Arizona%' OR brewery_name IN ('Four Peaks Brewing Company', 'Arizona Wilderness Brewing Company', 'Historic Brewing Company', 'Dragoon Brewing Company', 'SanTan Brewing Company', 'Oak Creek Brewery', 'Mother Road Brewing Company');