export interface Database {
  public: {
    Tables: {
      blog_posts: {
        Row: {
          id: string;
          title: string;
          slug: string;
          excerpt: string | null;
          content: string;
          featured_image_url: string | null;
          state: string;
          week_number: number;
          read_time: number | null;
          published_at: string | null;
          created_at: string;
          updated_at: string;
          seo_meta_description: string | null;
          seo_keywords: string[] | null;
          view_count: number | null;
          is_featured: boolean | null;
          status: string;
          author_id: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          excerpt?: string | null;
          content: string;
          featured_image_url?: string | null;
          state: string;
          week_number: number;
          read_time?: number | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
          seo_meta_description?: string | null;
          seo_keywords?: string[] | null;
          view_count?: number | null;
          is_featured?: boolean | null;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          excerpt?: string | null;
          content?: string;
          featured_image_url?: string | null;
          state?: string;
          week_number?: number;
          read_time?: number | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
          seo_meta_description?: string | null;
          seo_keywords?: string[] | null;
          view_count?: number | null;
          is_featured?: boolean | null;
        };
      };
      beer_reviews: {
        Row: {
          id: string;
          blog_post_id: string | null;
          brewery_name: string;
          beer_name: string;
          beer_style: string;
          abv: number | null;
          rating: number | null;
          tasting_notes: string | null;
          unique_feature: string | null;
          brewery_story: string | null;
          brewery_location: string | null;
          image_url: string | null;
          day_of_week: number | null;
          created_at: string;
          // Extended fields for BrewQuest Chronicles
          state_code: string | null;
          state_name: string | null;
          week_number: number | null;
          ibu: number | null;
          description: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          blog_post_id?: string | null;
          brewery_name: string;
          beer_name: string;
          beer_style: string;
          abv?: number | null;
          rating?: number | null;
          tasting_notes?: string | null;
          unique_feature?: string | null;
          brewery_story?: string | null;
          brewery_location?: string | null;
          image_url?: string | null;
          day_of_week?: number | null;
          created_at?: string;
          // Extended fields for BrewQuest Chronicles
          state_code?: string | null;
          state_name?: string | null;
          week_number?: number | null;
          ibu?: number | null;
          description?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          blog_post_id?: string | null;
          brewery_name?: string;
          beer_name?: string;
          beer_style?: string;
          abv?: number | null;
          rating?: number | null;
          tasting_notes?: string | null;
          unique_feature?: string | null;
          brewery_story?: string | null;
          brewery_location?: string | null;
          image_url?: string | null;
          day_of_week?: number | null;
          created_at?: string;
          // Extended fields for BrewQuest Chronicles
          state_code?: string | null;
          state_name?: string | null;
          week_number?: number | null;
          ibu?: number | null;
          description?: string | null;
          updated_at?: string | null;
        };
      };
      social_posts: {
        Row: {
          id: string;
          beer_review_id: string | null;
          platform: string;
          content: string;
          image_url: string | null;
          hashtags: string[] | null;
          scheduled_time: string | null;
          posted_at: string | null;
          engagement_metrics: any | null;
          status: string | null;
        };
        Insert: {
          id?: string;
          beer_review_id?: string | null;
          platform: string;
          content: string;
          image_url?: string | null;
          hashtags?: string[] | null;
          scheduled_time?: string | null;
          posted_at?: string | null;
          engagement_metrics?: any | null;
          status?: string | null;
        };
        Update: {
          id?: string;
          beer_review_id?: string | null;
          platform?: string;
          content?: string;
          image_url?: string | null;
          hashtags?: string[] | null;
          scheduled_time?: string | null;
          posted_at?: string | null;
          engagement_metrics?: any | null;
          status?: string | null;
        };
      };
      newsletter_subscribers: {
        Row: {
          id: string;
          email: string;
          first_name: string | null;
          subscribed_at: string;
          is_active: boolean | null;
          preferences: any | null;
        };
        Insert: {
          id?: string;
          email: string;
          first_name?: string | null;
          subscribed_at?: string;
          is_active?: boolean | null;
          preferences?: any | null;
        };
        Update: {
          id?: string;
          email?: string;
          first_name?: string | null;
          subscribed_at?: string;
          is_active?: boolean | null;
          preferences?: any | null;
        };
      };
      page_analytics: {
        Row: {
          id: string;
          page_path: string;
          page_title: string | null;
          visitor_id: string | null;
          session_id: string;
          timestamp: string;
          referrer: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_term: string | null;
          user_agent: string | null;
          ip_address: string | null;
          country: string | null;
          region: string | null;
          city: string | null;
          device_type: string | null;
          browser: string | null;
          os: string | null;
          screen_resolution: string | null;
          time_on_page: number | null;
          bounce: boolean | null;
          conversion_event: string | null;
          blog_post_id: string | null;
          beer_review_id: string | null;
          state_code: string | null;
        };
        Insert: {
          id?: string;
          page_path: string;
          page_title?: string | null;
          visitor_id?: string | null;
          session_id: string;
          timestamp?: string;
          referrer?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          country?: string | null;
          region?: string | null;
          city?: string | null;
          device_type?: string | null;
          browser?: string | null;
          os?: string | null;
          screen_resolution?: string | null;
          time_on_page?: number | null;
          bounce?: boolean | null;
          conversion_event?: string | null;
          blog_post_id?: string | null;
          beer_review_id?: string | null;
          state_code?: string | null;
        };
        Update: {
          id?: string;
          page_path?: string;
          page_title?: string | null;
          visitor_id?: string | null;
          session_id?: string;
          timestamp?: string;
          referrer?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          country?: string | null;
          region?: string | null;
          city?: string | null;
          device_type?: string | null;
          browser?: string | null;
          os?: string | null;
          screen_resolution?: string | null;
          time_on_page?: number | null;
          bounce?: boolean | null;
          conversion_event?: string | null;
          blog_post_id?: string | null;
          beer_review_id?: string | null;
          state_code?: string | null;
        };
      };
      social_campaigns: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          campaign_type: string | null;
          start_date: string;
          end_date: string | null;
          budget: number | null;
          target_metrics: any | null;
          actual_metrics: any | null;
          states_included: string[] | null;
          platforms: string[] | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          campaign_type?: string | null;
          start_date: string;
          end_date?: string | null;
          budget?: number | null;
          target_metrics?: any | null;
          actual_metrics?: any | null;
          states_included?: string[] | null;
          platforms?: string[] | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          campaign_type?: string | null;
          start_date?: string;
          end_date?: string | null;
          budget?: number | null;
          target_metrics?: any | null;
          actual_metrics?: any | null;
          states_included?: string[] | null;
          platforms?: string[] | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      state_analytics: {
        Row: {
          id: string;
          state_code: string | null;
          interaction_type: string;
          session_id: string;
          user_agent: string | null;
          device_type: string | null;
          source_page: string | null;
          timestamp: string;
          duration_ms: number | null;
          metadata: any | null;
          ip_address: string | null;
          referrer: string | null;
          conversion_event: string | null;
          user_id: string | null;
        };
        Insert: {
          id?: string;
          state_code?: string | null;
          interaction_type: string;
          session_id: string;
          user_agent?: string | null;
          device_type?: string | null;
          source_page?: string | null;
          timestamp?: string;
          duration_ms?: number | null;
          metadata?: any | null;
          ip_address?: string | null;
          referrer?: string | null;
          conversion_event?: string | null;
          user_id?: string | null;
        };
        Update: {
          id?: string;
          state_code?: string | null;
          interaction_type?: string;
          session_id?: string;
          user_agent?: string | null;
          device_type?: string | null;
          source_page?: string | null;
          timestamp?: string;
          duration_ms?: number | null;
          metadata?: any | null;
          ip_address?: string | null;
          referrer?: string | null;
          conversion_event?: string | null;
          user_id?: string | null;
        };
      };
      map_interactions: {
        Row: {
          id: string;
          state_code: string;
          action: string;
          timestamp: string;
          user_agent: string | null;
          session_id: string;
          metadata: any | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          state_code: string;
          action: string;
          timestamp?: string;
          user_agent?: string | null;
          session_id: string;
          metadata?: any | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          state_code?: string;
          action?: string;
          timestamp?: string;
          user_agent?: string | null;
          session_id?: string;
          metadata?: any | null;
          created_at?: string;
        };
      };
      brewery_features: {
        Row: {
          id: string;
          state_code: string | null;
          brewery_name: string;
          brewery_type: string | null;
          city: string;
          address: string | null;
          website_url: string | null;
          founded_year: number | null;
          specialty_styles: string[] | null;
          signature_beers: string[] | null;
          brewery_description: string | null;
          why_featured: string | null;
          visit_priority: number | null;
          social_media: any | null;
          awards: string[] | null;
          capacity_barrels: number | null;
          taproom_info: any | null;
          is_active: boolean;
          featured_week: number | null;
          created_at: string;
          updated_at: string;
          distribution_area: string | null;
          tour_availability: boolean | null;
          food_service: boolean | null;
          outdoor_seating: boolean | null;
          family_friendly: boolean | null;
          dog_friendly: boolean | null;
          parking_availability: string | null;
          accessibility_features: string[] | null;
          seasonal_hours: any | null;
        };
        Insert: {
          id?: string;
          state_code?: string | null;
          brewery_name: string;
          brewery_type?: string | null;
          city: string;
          address?: string | null;
          website_url?: string | null;
          founded_year?: number | null;
          specialty_styles?: string[] | null;
          signature_beers?: string[] | null;
          brewery_description?: string | null;
          why_featured?: string | null;
          visit_priority?: number | null;
          social_media?: any | null;
          awards?: string[] | null;
          capacity_barrels?: number | null;
          taproom_info?: any | null;
          is_active?: boolean;
          featured_week?: number | null;
          created_at?: string;
          updated_at?: string;
          distribution_area?: string | null;
          tour_availability?: boolean | null;
          food_service?: boolean | null;
          outdoor_seating?: boolean | null;
          family_friendly?: boolean | null;
          dog_friendly?: boolean | null;
          parking_availability?: string | null;
          accessibility_features?: string[] | null;
          seasonal_hours?: any | null;
        };
        Update: {
          id?: string;
          state_code?: string | null;
          brewery_name?: string;
          brewery_type?: string | null;
          city?: string;
          address?: string | null;
          website_url?: string | null;
          founded_year?: number | null;
          specialty_styles?: string[] | null;
          signature_beers?: string[] | null;
          brewery_description?: string | null;
          why_featured?: string | null;
          visit_priority?: number | null;
          social_media?: any | null;
          awards?: string[] | null;
          capacity_barrels?: number | null;
          taproom_info?: any | null;
          is_active?: boolean;
          featured_week?: number | null;
          created_at?: string;
          updated_at?: string;
          distribution_area?: string | null;
          tour_availability?: boolean | null;
          food_service?: boolean | null;
          outdoor_seating?: boolean | null;
          family_friendly?: boolean | null;
          dog_friendly?: boolean | null;
          parking_availability?: string | null;
          accessibility_features?: string[] | null;
          seasonal_hours?: any | null;
        };
      };
      journey_milestones: {
        Row: {
          id: string;
          milestone_type: string;
          title: string;
          description: string;
          state_code: string | null;
          week_number: number | null;
          milestone_date: string;
          metric_value: number | null;
          metric_unit: string | null;
          celebration_level: string;
          social_media_posted: boolean;
          blog_post_id: string | null;
          metadata: any | null;
          is_public: boolean;
          created_at: string;
          social_engagement_count: number;
          newsletter_featured: boolean;
          press_coverage: string[] | null;
          community_reaction_score: number | null;
        };
        Insert: {
          id?: string;
          milestone_type: string;
          title: string;
          description: string;
          state_code?: string | null;
          week_number?: number | null;
          milestone_date?: string;
          metric_value?: number | null;
          metric_unit?: string | null;
          celebration_level?: string;
          social_media_posted?: boolean;
          blog_post_id?: string | null;
          metadata?: any | null;
          is_public?: boolean;
          created_at?: string;
          social_engagement_count?: number;
          newsletter_featured?: boolean;
          press_coverage?: string[] | null;
          community_reaction_score?: number | null;
        };
        Update: {
          id?: string;
          milestone_type?: string;
          title?: string;
          description?: string;
          state_code?: string | null;
          week_number?: number | null;
          milestone_date?: string;
          metric_value?: number | null;
          metric_unit?: string | null;
          celebration_level?: string;
          social_media_posted?: boolean;
          blog_post_id?: string | null;
          metadata?: any | null;
          is_public?: boolean;
          created_at?: string;
          social_engagement_count?: number;
          newsletter_featured?: boolean;
          press_coverage?: string[] | null;
          community_reaction_score?: number | null;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
} 